--- 
- hosts: all
  sudo: yes
  roles:
    - martinmicunda.common
    - martinmicunda.nodejs
    - martinmicunda.ionic
    - laggyluke.direnv
  
  tasks:
  - name: cd into the mobile client source folder
    shell: echo  "cd ~/mobileclient" >> /home/vagrant/.bash_profile

