---
- hosts: all
  sudo: yes
  roles:
    - martinmicunda.common
    - nodesource.node
    - laggyluke.direnv

  tasks:
  - name: cd into the mobile client source folder
    shell: echo  "cd ~/mobileclient" >> /home/vagrant/.bash_profile

